/* Auth */
export const SIGN_IN_USER = 'SIGN_IN_USER'
export const SIGN_UP_USER = 'SIGN_UP_USER'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'

/* Project */
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE'
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS'
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS'
export const PROJECTS_FETCH_FAILURE = 'PROJECTS_FETCH_FAILURE'
