/* User */
export const SIGN_IN_USER = 'SIGN_IN_USER'
export const SIGN_UP_USER = 'SIGN_UP_USER'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'

/* Project */
export const PROJECT_CREATED_SUCCESS = 'PROJECT_CREATED_SUCCESS'
export const PROJECT_UPDATED_SUCCESS = 'PROJECT_UPDATED_SUCCESS'
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE'
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS'
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS'
export const PROJECTS_FETCH_FAILURE = 'PROJECTS_FETCH_FAILURE'
export const PROJECT_EXIT = 'PROJECT_EXIT'
export const PROJECT_ADMIN_DELETED = 'PROJECT_ADMIN_DELETED'
export const PROJECT_ADMIN_UPDATED = 'PROJECT_ADMIN_UPDATED'
export const PROJECT_ADMINS_FETCHED = 'PROJECT_ADMINS_FETCHED'

/* Admin Panel */
export const TRANSLATE_FETCH_SUCCESS = 'TRANSLATE_FETCH_SUCCESS'

/* Documents */
export const DOCUMENT_CREATE_SUCCESS = 'DOCUMENT_CREATE_SUCCESS'
export const DOCUMENT_FETCH_SUCCESS = 'DOCUMENT_FETCH_SUCCESS'
export const DOCUMENTS_FETCH_SUCCESS = 'DOCUMENTS_FETCH_SUCCESS'
export const CREATING_DOCUMENT = 'CREATING_DOCUMENT'
export const EDIT_DOCUMENT = 'EDIT_DOCUMENT'

/* Conventions */
export const EDITING_CONVENTION = 'EDITING_CONVENTION'
export const CONVENTION_UPDATED = 'CONVENTION_UPDATED'

/* Access rights*/
export const GET_NEW_MEMBERS_LIST = 'GET_NEW_MEMBERS_LIST'
export const GET_CURRENT_MEMBERS_LIST = 'GET_CURRENT_MEMBERS_LIST'

/* Project members */
export const ACTIVE_MEMBERS_FETCHED_SUCCESS = 'ACTIVE_MEMBERS_FETCHED_SUCCESS'
export const PENDING_MEMBERS_FETCHED_SUCCESS = 'PENDING_MEMBERS_FETCHED_SUCCESS'
export const CREATING_PROJECT_MEMBER = 'CREATING_PROJECT_MEMBER'
export const PROJECT_MEMBER_CREATED = 'PROJECT_MEMBER_CREATED'
export const PROJECT_MEMBER_UPDATED = 'PROJECT_MEMBER_UPDATED'

/* Disciplines */
export const DISCIPLINES_FETCHED = 'DISCIPLINES_FETCHED'
export const DISCIPLINES_UPDATED = 'DISCIPLINES_UPDATED'
export const DISCIPLINES_DELETED = 'DISCIPLINES_DELETED'
export const DISCIPLINE_CREATED = 'DISCIPLINE_CREATED'

/* Roles */
export const ROLES_FETCHED = 'ROLES_FETCHED'
export const ROLE_UPDATED = 'ROLES_UPDATED'
export const ROLE_DELETED = 'ROLES_DELETED'
export const ROLE_CREATED = 'ROLE_CREATED'

/* Folders */
export const FOLDER_CREATED = 'FOLDER_CREATED'
export const FOLDERS_FETCHED = 'FOLDERS_FETCHED'
export const EDITING_FOLDER = 'EDITING_FOLDER'
export const DOCUMENT_ADDED = 'DOCUMENT_ADDED'