/* User */
export const SIGN_IN_USER = 'SIGN_IN_USER'
export const SIGN_UP_USER = 'SIGN_UP_USER'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'

/* Project */
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAILURE = 'PROJECT_CREATE_FAILURE'
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS'
export const PROJECT_FETCH_SUCCESS = 'PROJECT_FETCH_SUCCESS'
export const PROJECTS_FETCH_FAILURE = 'PROJECTS_FETCH_FAILURE'
export const PROJECT_EXIT = 'PROJECT_EXIT'

/* Admin Panel */
export const TRANSLATE_FETCH_SUCCESS = 'TRANSLATE_FETCH_SUCCESS'

/* Documents */
export const DOCUMENT_CREATE_SUCCESS = 'DOCUMENT_CREATE_SUCCESS'
export const DOCUMENT_FETCH_SUCCESS = 'DOCUMENT_FETCH_SUCCESS'
export const DOCUMENTS_FETCH_SUCCESS = 'DOCUMENTS_FETCH_SUCCESS'
export const EDITING_CONVENTION = 'EDITING_CONVENTION'

